name: Publish Release
on:
  push:
    tags:
      - release-* # --> version
      - pre-*     # --> tag-suffix

#  - clean Docker cache
#  - For each profile,
#    - build: build-image.sh ${tag} ${profile}

#    - push to Dockerhub as `texlive-$profile:{$version,latest}`
#    - create Github release

#    - push to Dockerhub as `texlive-$profile:$tag-suffix`
#    - create Github pre-release

jobs:
  publish-release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Build images
        run: echo "nyi (make images)"
      - name: Publish images
        run: echo "nyi (publish images)"
        env:
          DOCKERHUB_ACCESS_TOKEN: {{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Create Github release
        run: echo "nyi (create release)"
        # --> https://github.com/actions/create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
