name: Create Monthly Release
on:
  schedule:
    - cron:  '0 0 1 * *'

env:
  TEXLIVE_INSTALLER_IMAGE: "texlive-installer:latest"

jobs:
  make-tag:
    name: Make Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Obtain Installer
        run: .github/scripts/build-installer-image.sh
      - name: Determine TeXlive Version
        run: .github/scripts/make-release-tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_REITZIG }}
          # Note: use "real" access token so workflow trigger isn't surpressed
          #       cf https://github.community/t5/GitHub-Actions/Tag-created-by-API-does-not-trigger-create/m-p/36686/highlight/true#M2653
  # --> will trigger `test-and-publish.yml` with a `create` event

